# Generated by Django 2.2.6 on 2020-04-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200422_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
